/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/mh/catkin_ws/src/kurosp/srv/BlockSendTrajectory.srv
 *
 */


#ifndef KUROSP_MESSAGE_BLOCKSENDTRAJECTORY_H
#define KUROSP_MESSAGE_BLOCKSENDTRAJECTORY_H

#include <ros/service_traits.h>


#include <kurosp/BlockSendTrajectoryRequest.h>
#include <kurosp/BlockSendTrajectoryResponse.h>


namespace kurosp
{

struct BlockSendTrajectory
{

typedef BlockSendTrajectoryRequest Request;
typedef BlockSendTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BlockSendTrajectory
} // namespace kurosp


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kurosp::BlockSendTrajectory > {
  static const char* value()
  {
    return "244e5565eb5f6feacf78a0491f04db4a";
  }

  static const char* value(const ::kurosp::BlockSendTrajectory&) { return value(); }
};

template<>
struct DataType< ::kurosp::BlockSendTrajectory > {
  static const char* value()
  {
    return "kurosp/BlockSendTrajectory";
  }

  static const char* value(const ::kurosp::BlockSendTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::kurosp::BlockSendTrajectoryRequest> should match 
// service_traits::MD5Sum< ::kurosp::BlockSendTrajectory > 
template<>
struct MD5Sum< ::kurosp::BlockSendTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kurosp::BlockSendTrajectory >::value();
  }
  static const char* value(const ::kurosp::BlockSendTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kurosp::BlockSendTrajectoryRequest> should match 
// service_traits::DataType< ::kurosp::BlockSendTrajectory > 
template<>
struct DataType< ::kurosp::BlockSendTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::kurosp::BlockSendTrajectory >::value();
  }
  static const char* value(const ::kurosp::BlockSendTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kurosp::BlockSendTrajectoryResponse> should match 
// service_traits::MD5Sum< ::kurosp::BlockSendTrajectory > 
template<>
struct MD5Sum< ::kurosp::BlockSendTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kurosp::BlockSendTrajectory >::value();
  }
  static const char* value(const ::kurosp::BlockSendTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kurosp::BlockSendTrajectoryResponse> should match 
// service_traits::DataType< ::kurosp::BlockSendTrajectory > 
template<>
struct DataType< ::kurosp::BlockSendTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::kurosp::BlockSendTrajectory >::value();
  }
  static const char* value(const ::kurosp::BlockSendTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KUROSP_MESSAGE_BLOCKSENDTRAJECTORY_H
