/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/mh/catkin_ws/src/kurosp/msg/Info.msg
 *
 */


#ifndef KUROSP_MESSAGE_INFO_H
#define KUROSP_MESSAGE_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kurosp
{
template <class ContainerAllocator>
struct Info_
{
  typedef Info_<ContainerAllocator> Type;

  Info_()
    : response_mode(0)
    , response_ms(0)
    , traj_id(0)
    , run(false)
    , vel(0)
    , tol(0)
    , frame_type(0)  {
    }
  Info_(const ContainerAllocator& _alloc)
    : response_mode(0)
    , response_ms(0)
    , traj_id(0)
    , run(false)
    , vel(0)
    , tol(0)
    , frame_type(0)  {
    }



   typedef uint8_t _response_mode_type;
  _response_mode_type response_mode;

   typedef uint32_t _response_ms_type;
  _response_ms_type response_ms;

   typedef uint32_t _traj_id_type;
  _traj_id_type traj_id;

   typedef uint8_t _run_type;
  _run_type run;

   typedef uint32_t _vel_type;
  _vel_type vel;

   typedef uint32_t _tol_type;
  _tol_type tol;

   typedef uint8_t _frame_type_type;
  _frame_type_type frame_type;




  typedef boost::shared_ptr< ::kurosp::Info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kurosp::Info_<ContainerAllocator> const> ConstPtr;

}; // struct Info_

typedef ::kurosp::Info_<std::allocator<void> > Info;

typedef boost::shared_ptr< ::kurosp::Info > InfoPtr;
typedef boost::shared_ptr< ::kurosp::Info const> InfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kurosp::Info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kurosp::Info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kurosp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'kurosp': ['/home/mh/catkin_ws/src/kurosp/msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kurosp::Info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kurosp::Info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kurosp::Info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kurosp::Info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kurosp::Info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kurosp::Info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kurosp::Info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7be2d7c158064f808f034be3a19e5b8";
  }

  static const char* value(const ::kurosp::Info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7be2d7c158064f8ULL;
  static const uint64_t static_value2 = 0x08f034be3a19e5b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::kurosp::Info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kurosp/Info";
  }

  static const char* value(const ::kurosp::Info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kurosp::Info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 response_mode #= 3 # KUKA_RMODE_STREAM\n\
uint32 response_ms #= 20 # [ms]\n\
uint32 traj_id #= 666 # a trajectory id\n\
bool run #= 1 # YES\n\
uint32 vel #= 200 # [mm/s]\n\
uint32 tol #= 20 # [mm]\n\
uint8 frame_type #= 1 # KUKA_CARTESIAN\n\
";
  }

  static const char* value(const ::kurosp::Info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kurosp::Info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response_mode);
      stream.next(m.response_ms);
      stream.next(m.traj_id);
      stream.next(m.run);
      stream.next(m.vel);
      stream.next(m.tol);
      stream.next(m.frame_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kurosp::Info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kurosp::Info_<ContainerAllocator>& v)
  {
    s << indent << "response_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.response_mode);
    s << indent << "response_ms: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.response_ms);
    s << indent << "traj_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.traj_id);
    s << indent << "run: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.run);
    s << indent << "vel: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.vel);
    s << indent << "tol: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.tol);
    s << indent << "frame_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.frame_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUROSP_MESSAGE_INFO_H
