(cl:defpackage kurosp-srv
  (:use )
  (:export
   "SENDTRAJECTORY"
   "<SENDTRAJECTORY-REQUEST>"
   "SENDTRAJECTORY-REQUEST"
   "<SENDTRAJECTORY-RESPONSE>"
   "SENDTRAJECTORY-RESPONSE"
   "BLOCKSENDTRAJECTORY"
   "<BLOCKSENDTRAJECTORY-REQUEST>"
   "BLOCKSENDTRAJECTORY-REQUEST"
   "<BLOCKSENDTRAJECTORY-RESPONSE>"
   "BLOCKSENDTRAJECTORY-RESPONSE"
  ))

