"""autogenerated by genpy from kurosp/XyzYprTrajectory.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import kurosp.msg

class XyzYprTrajectory(genpy.Message):
  _md5sum = "1c5a80a148196559c67debf2f7d074e4"
  _type = "kurosp/XyzYprTrajectory"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """Info info
XyzYpr[] frames

================================================================================
MSG: kurosp/Info
uint8 response_mode #= 3 # KUKA_RMODE_STREAM
uint32 response_ms #= 20 # [ms]
uint32 traj_id #= 666 # a trajectory id
bool run #= 1 # YES
uint32 vel #= 200 # [mm/s]
uint32 tol #= 20 # [mm]
uint8 frame_type #= 1 # KUKA_CARTESIAN

================================================================================
MSG: kurosp/XyzYpr
float64[6] xyzypr

"""
  __slots__ = ['info','frames']
  _slot_types = ['kurosp/Info','kurosp/XyzYpr[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       info,frames

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(XyzYprTrajectory, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.info is None:
        self.info = kurosp.msg.Info()
      if self.frames is None:
        self.frames = []
    else:
      self.info = kurosp.msg.Info()
      self.frames = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_B2IB2IB.pack(_x.info.response_mode, _x.info.response_ms, _x.info.traj_id, _x.info.run, _x.info.vel, _x.info.tol, _x.info.frame_type))
      length = len(self.frames)
      buff.write(_struct_I.pack(length))
      for val1 in self.frames:
        buff.write(_struct_6d.pack(*val1.xyzypr))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.info is None:
        self.info = kurosp.msg.Info()
      if self.frames is None:
        self.frames = None
      end = 0
      _x = self
      start = end
      end += 19
      (_x.info.response_mode, _x.info.response_ms, _x.info.traj_id, _x.info.run, _x.info.vel, _x.info.tol, _x.info.frame_type,) = _struct_B2IB2IB.unpack(str[start:end])
      self.info.run = bool(self.info.run)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.frames = []
      for i in range(0, length):
        val1 = kurosp.msg.XyzYpr()
        start = end
        end += 48
        val1.xyzypr = _struct_6d.unpack(str[start:end])
        self.frames.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_B2IB2IB.pack(_x.info.response_mode, _x.info.response_ms, _x.info.traj_id, _x.info.run, _x.info.vel, _x.info.tol, _x.info.frame_type))
      length = len(self.frames)
      buff.write(_struct_I.pack(length))
      for val1 in self.frames:
        buff.write(val1.xyzypr.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.info is None:
        self.info = kurosp.msg.Info()
      if self.frames is None:
        self.frames = None
      end = 0
      _x = self
      start = end
      end += 19
      (_x.info.response_mode, _x.info.response_ms, _x.info.traj_id, _x.info.run, _x.info.vel, _x.info.tol, _x.info.frame_type,) = _struct_B2IB2IB.unpack(str[start:end])
      self.info.run = bool(self.info.run)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.frames = []
      for i in range(0, length):
        val1 = kurosp.msg.XyzYpr()
        start = end
        end += 48
        val1.xyzypr = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=6)
        self.frames.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_6d = struct.Struct("<6d")
_struct_B2IB2IB = struct.Struct("<B2IB2IB")
