"""autogenerated by genpy from kurosp/XyzYprState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class XyzYprState(genpy.Message):
  _md5sum = "4ab2881d41b267db4a3a1e1808a48c72"
  _type = "kurosp/XyzYprState"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 status
int32 id
int32 tick
float64[6] xyzypr


"""
  __slots__ = ['status','id','tick','xyzypr']
  _slot_types = ['int32','int32','int32','float64[6]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       status,id,tick,xyzypr

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(XyzYprState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.status is None:
        self.status = 0
      if self.id is None:
        self.id = 0
      if self.tick is None:
        self.tick = 0
      if self.xyzypr is None:
        self.xyzypr = [0.,0.,0.,0.,0.,0.]
    else:
      self.status = 0
      self.id = 0
      self.tick = 0
      self.xyzypr = [0.,0.,0.,0.,0.,0.]

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3i.pack(_x.status, _x.id, _x.tick))
      buff.write(_struct_6d.pack(*self.xyzypr))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.status, _x.id, _x.tick,) = _struct_3i.unpack(str[start:end])
      start = end
      end += 48
      self.xyzypr = _struct_6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3i.pack(_x.status, _x.id, _x.tick))
      buff.write(self.xyzypr.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.status, _x.id, _x.tick,) = _struct_3i.unpack(str[start:end])
      start = end
      end += 48
      self.xyzypr = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=6)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3i = struct.Struct("<3i")
_struct_6d = struct.Struct("<6d")
